# Assignment 6 (Regression)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import LogisticRegression

## Question 1

In [2]:
q1 = pd.read_excel("Real estate valuation data set.xlsx")

In [3]:
q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [4]:
q1.insert(0,"X0",1)
q1

,X0,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,1,2012.916667,32.0,84.87882,10,24.98298,121.54024,37.9
1,1,2,2012.916667,19.5,306.59470,9,24.98034,121.53951,42.2
2,1,3,2013.583333,13.3,561.98450,5,24.98746,121.54391,47.3
3,1,4,2013.500000,13.3,561.98450,5,24.98746,121.54391,54.8
4,1,5,2012.833333,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...,...
409,1,410,2013.000000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,1,411,2012.666667,5.6,90.45606,9,24.97433,121.54310,50.0
411,1,412,2013.250000,18.8,390.96960,7,24.97923,121.53986,40.6
412,1,413,2013.000000,8.1,104.81010,5,24.96674,121.54067,52.5
413,1,414,2013.500000,6.5,90.45606,9,24.97433,121.54310,63.9

In [5]:
for i in [80,60,70,90]:
    q1_train = q1.iloc[:(len(q1)*i)//100]
    q1_test = q1.iloc[len(q1)-(len(q1)*i)//100:]
    
    print('\033[1m'+f"For {i}:{100-i} Split"+ '\033[0m')

    y_1_train = q1_train["Y house price of unit area"]
    X_train = q1_train[["X0","X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
    X_train = X_train.values
    X_train = np.asmatrix(X_train)
    y_1_train = y_1_train.values

    x_xt_inv = np.linalg.inv(np.matmul(X_train.transpose(),X_train))
    beta_1 = np.matmul(np.matmul(x_xt_inv,X_train.transpose()),y_1_train)

    for i in range(7):
        if i == 0:
            print("Intercept: ",beta_1[0,0])
        else:
            print(f"Beta {i}: ",beta_1[0,i])

    X_test = q1_test[["X0","X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
    X_test = X_test.values
    y_1_pred = np.matmul(beta_1,X_test.transpose())
    y_1_test = q1_test["Y house price of unit area"]
    y_1_test = np.matrix(y_1_test.values)
    y_1_err = np.subtract(y_1_test,y_1_pred)
    error_1 = np.dot(y_1_err,y_1_err.transpose())
    error_1 = error_1[0,0]
    print(f"Mean Squared Error for Y (House Price of unit area) : {error_1}")

    rss = error_1
    tss_vec = y_1_test - np.mean(y_1_test)
    tss = np.dot(tss_vec,tss_vec.transpose())
    tss = tss[0,0]
    r_square = 1 - (rss/tss)
    print(f"Coefficient of Determination (r^2): {r_square}\n")

For 80:20 Split
Intercept:  -15604.504776727004
Beta 1:  5.1464947343705525
Beta 2:  -0.28678341546353125
Beta 3:  -0.0041539094701209655
Beta 4:  1.1780400761882563
Beta 5:  249.53093915765558
Beta 6:  -7.767012091699044
Mean Squared Error for Y (House Price of unit area) : 27941.772818239984
Coefficient of Determination (r^2): 0.5498708349162247

For 60:40 Split
Intercept:  -15993.909054818678
Beta 1:  3.813851175121054
Beta 2:  -0.2920001558449369
Beta 3:  -0.0037800314845066628
Beta 4:  1.2447769102925363
Beta 5:  239.8881424790498
Beta 6:  19.490242218630115
Mean Squared Error for Y (House Price of unit area) : 20853.29567260427
Coefficient of Determination (r^2): 0.5511217329881383

For 70:30 Split
Intercept:  -13872.443088097085
Beta 1:  4.595548272347376
Beta 2:  -0.3021102376129876
Beta 3:  -0.0042217401627322685
Beta 4:  1.1013268035536345
Beta 5:  264.5189391308489
Beta 6:  -15.965078308184516
Mean Squared Error for Y (House Price of unit area) : 24561.254269896126
Coefficient of Determination (r^2): 0.5326899750272656

For 90:10 Split
Intercept:  -15684.751252316768
Beta 1:  5.356651360156534
Beta 2:  -0.2723048283280348
Beta 3:  -0.004299934810695619
Beta 4:  1.1319782445171789
Beta 5:  252.7512230089195
Beta 6:  -11.248970254058818
Mean Squared Error for Y (House Price of unit area) : 29790.956686661782
Coefficient of Determination (r^2): 0.5714527786767036

### Ridge Model:

In [6]:
for alpha in [0.001, 0.005, 0.01, 0.05, 0.1]:
    print('\033[1m'+f"\nALPHA = {alpha} \n"+ '\033[0m')
    for i in [80,60,70,90]:
        q1_train = q1.iloc[:(len(q1)*i)//100]
        q1_test = q1.iloc[len(q1)-(len(q1)*i)//100:]
    
        print('\033[1m'+f"For {i}:{100-i} Split"+ '\033[0m')

        y_1_train = q1_train["Y house price of unit area"]
        X_train = q1_train[["X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
        X_test = q1_test[["X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
        y_1_test = q1_test["Y house price of unit area"]

        rr = Ridge(alpha=alpha)
        rr.fit(X_train,y_1_train)
    
        Ridge_test_score = rr.score(X_test, y_1_test)
    
        y_1_pred = rr.predict(X_test)
        y_1_test = np.matrix(y_1_test.values)
        y_1_err = np.subtract(y_1_test,y_1_pred)
        error_1 = np.dot(y_1_err,y_1_err.transpose())
        error_1 = error_1[0,0]
        print(f"Mean Squared Error for Y (House Price of unit area) : {error_1}")
        print(f"Coefficient of Determination (r^2): {Ridge_test_score}")

ALPHA = 0.001

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 27934.668485932627
Coefficient of Determination (r^2): 0.5499852824565004
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 20848.209199080484
Coefficient of Determination (r^2): 0.5512312220327671
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24525.92779356895
Coefficient of Determination (r^2): 0.5333621074987284
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29781.55155154605
Coefficient of Determination (r^2): 0.5715880729058354

ALPHA = 0.005

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 27936.834515625764
Coefficient of Determination (r^2): 0.5499503887100061
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 20862.582357145235
Coefficient of Determination (r^2): 0.5509218321701341
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24441.031211707195
Coefficient of Determination (r^2): 0.5349773761390823
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29772.26932231803
Coefficient of Determination (r^2): 0.5717215991159934

ALPHA = 0.01

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 27979.478251351415
Coefficient of Determination (r^2): 0.5492634176547655
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 20917.81775674319
Coefficient of Determination (r^2): 0.5497328608517151
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24410.172497137883
Coefficient of Determination (r^2): 0.535564503592654
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29800.540240284496
Coefficient of Determination (r^2): 0.57131491787154

ALPHA = 0.05

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 28473.900143111816
Coefficient of Determination (r^2): 0.5412985073827885
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 21356.07738592507
Coefficient of Determination (r^2): 0.5402990895218975
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24670.393210958933
Coefficient of Determination (r^2): 0.530613463758211
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 30267.152203188976
Coefficient of Determination (r^2): 0.5646026372877999

ALPHA = 0.1

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 28823.269810755653
Coefficient of Determination (r^2): 0.5356703220194223
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 21602.721318597298
Coefficient of Determination (r^2): 0.534989947849277
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24912.656817256677
Coefficient of Determination (r^2): 0.5260040814088842
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 30644.712984335354
Coefficient of Determination (r^2): 0.5591713708352735

### Lasso Model

In [7]:
for alpha in [0.001, 0.005, 0.01, 0.05, 0.1]:
    print('\033[1m'+f"\nALPHA = {alpha} \n"+ '\033[0m')
    for i in [80,60,70,90]:
        q1_train = q1.iloc[:(len(q1)*i)//100]
        q1_test = q1.iloc[len(q1)-(len(q1)*i)//100:]
    
        print('\033[1m'+f"For {i}:{100-i} Split"+ '\033[0m')

        y_1_train = q1_train["Y house price of unit area"]
        X_train = q1_train[["X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
        X_test = q1_test[["X1 transaction date","X2 house age","X3 distance to the nearest MRT station","X4 number of convenience stores","X5 latitude","X6 longitude"]]
        y_1_test = q1_test["Y house price of unit area"]

        lasso = Lasso(alpha=alpha)
        lasso.fit(X_train,y_1_train)
    
        Lasso_test_score = lasso.score(X_test, y_1_test)
    
        y_1_pred = lasso.predict(X_test)
        y_1_test = np.matrix(y_1_test.values)
        y_1_err = np.subtract(y_1_test,y_1_pred)
        error_1 = np.dot(y_1_err,y_1_err.transpose())
        error_1 = error_1[0,0]
        print(f"Mean Squared Error for Y (House Price of unit area) : {error_1}")
        print(f"Coefficient of Determination (r^2): {Ridge_test_score}")

ALPHA = 0.001

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 27940.469029102012
Coefficient of Determination (r^2): 0.5591713708352735
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 20830.444639711975
Coefficient of Determination (r^2): 0.5591713708352735
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24542.959882088682
Coefficient of Determination (r^2): 0.5591713708352735
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29789.336115714224
Coefficient of Determination (r^2): 0.5591713708352735

ALPHA = 0.005

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 27969.670129485155
Coefficient of Determination (r^2): 0.5591713708352735
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 20868.657733199714
Coefficient of Determination (r^2): 0.5591713708352735
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24454.40216112337
Coefficient of Determination (r^2): 0.5591713708352735
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29806.510564491407
Coefficient of Determination (r^2): 0.5591713708352735

ALPHA = 0.01

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 28149.70953259692
Coefficient of Determination (r^2): 0.5591713708352735
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 21026.572981632995
Coefficient of Determination (r^2): 0.5591713708352735
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 24466.53962006301
Coefficient of Determination (r^2): 0.5591713708352735
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 29979.66996762766
Coefficient of Determination (r^2): 0.5591713708352735

ALPHA = 0.05

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 29567.618651941815
Coefficient of Determination (r^2): 0.5591713708352735
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 22108.322131661145
Coefficient of Determination (r^2): 0.5591713708352735
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 25455.97393980162
Coefficient of Determination (r^2): 0.5591713708352735
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 31555.74716914916
Coefficient of Determination (r^2): 0.5591713708352735

ALPHA = 0.1

For 80:20 Split
Mean Squared Error for Y (House Price of unit area) : 29559.382438842105
Coefficient of Determination (r^2): 0.5591713708352735
For 60:40 Split
Mean Squared Error for Y (House Price of unit area) : 22171.467178003022
Coefficient of Determination (r^2): 0.5591713708352735
For 70:30 Split
Mean Squared Error for Y (House Price of unit area) : 25477.0481620396
Coefficient of Determination (r^2): 0.5591713708352735
For 90:10 Split
Mean Squared Error for Y (House Price of unit area) : 31565.838926471326
Coefficient of Determination (r^2): 0.5591713708352735

## Question 2

In [8]:
q2 = pd.read_csv("haberman.data",delimiter=",",header = None)

In [9]:
q2 = q2.set_axis(['X1', 'X2', 'X3', 'Y'], axis=1, inplace=False)

In [10]:
q2

     X1  X2  X3  Y
0    30  64   1  1
1    30  62   3  1
2    30  65   0  1
3    31  59   2  1
4    31  65   4  1
..   ..  ..  .. ..
301  75  62   1  1
302  76  67   0  1
303  77  65   3  1
304  78  65   1  2
305  83  58   2  2

[306 rows x 4 columns]

In [11]:
lr = LogisticRegression()
for i in [80,60,70,90]:
    q2_train = q2.iloc[:(len(q2)*i)//100]
    q2_test = q2.iloc[len(q2)-(len(q2)*i)//100:]
    
    print('\033[1m'+f"For {i}:{100-i} Split"+ '\033[0m')

    y_2_train = q2_train["Y"]
    X_train = q2_train[["X1","X2","X3"]]
    X_test = q2_test[["X1","X2","X3"]]
    y_2_test = q2_test["Y"]
    
    lr = LogisticRegression()
    lr.fit(X_train,y_2_train)
    coefficients = lr.coef_
    intercept = lr.intercept_
    
    print(f"Intercept = {intercept[0]}")
    for j in range(3):
        print(f"Beta {j+1} = {coefficients[0,j]}")
    
    print("\nPredicted Survival Status: ",lr.predict(X_test),"\n")
    
    y_2_pred = lr.predict(X_test)
    y_2_test = y_2_test.values
    sum = 0
    
    diff = np.subtract(y_2_pred,y_2_test)
    diff = list(diff)
    
    for element in diff:
        if element != 0:
            sum += 1
    error = sum/len(y_2_test)
    
    print(f"Classification Error : {error} \n")

For 80:20 Split
Intercept = -5.4234165184071115
Beta 1 = 0.029656313755949317
Beta 2 = 0.04008675408385644
Beta 3 = 0.08963593146695155

Predicted Survival Status:  [2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1
 1 2 1 1 2 1 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1
 1 1 1 1 1 2 1 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Classification Error : 0.27049180327868855

For 60:40 Split
Intercept = -9.423693236590127
Beta 1 = 0.07577231983858823
Beta 2 = 0.07283233607135667
Beta 3 = 0.08604077841900595

Predicted Survival Status:  [1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 2 2 1 1 1 1 1 1 2 1 2 1 1 1 2 1 2 2 1 1 1 2 1 1 1 2 1 2 2 1 2 1 1 1 1 1 1
 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 2 2 2 1 1 2 2 1 2 1 2 1 1
 1 2 2 1 2 1 2 2 2 2 1 1 1 1 1 1 2 2 2 1 2 2 1 2 1 2 2 2 1 2 2 1 2 2 1 2 1
 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

Classification Error : 0.4098360655737705

For 70:30 Split
Intercept = -6.216469108711946
Beta 1 = 0.03641483430167668
Beta 2 = 0.04833527908055663
Beta 3 = 0.0873114304155584

Predicted Survival Status:  [2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 2 1 1 1 1 1 2 1 1 2 1 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1
 2 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1
 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Classification Error : 0.24299065420560748

For 90:10 Split
Intercept = -4.040045863835293
Beta 1 = 0.02551334599470319
Beta 2 = 0.021207198182975177
Beta 3 = 0.08534333335314445

Predicted Survival Status:  [1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 2 1
 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2
 1 2 1 1 1 1 1 2 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Classification Error : 0.26545454545454544